"""HAL adapter for the Anvil OpenARM 2.0 bimanual arm (MuJoCo digital twin).

The Anvil OpenARM 2.0 (https://docs.anvil.bot/introduction/openarm-2.0)
is Anvil Robotics' manufactured variant of the standard OpenArm v2.
The 2.0 generation carries the OpenARM 2.0 wrist swap (J6 = radial /
ulnar deviation, J7 = flexion / extension — flipped relative to
OpenArm 1.0), and the Anvil variant differs from the standard v2 in
exactly two documented joint ranges plus one part:

* **J1: +/-135 deg** (standard v2 ships -200..+80 deg in the MJCF sign
  convention) — symmetric base yaw on both arms.
* **J6: -45..+70 deg** (standard v2: +/-45 deg) — the extra +25 deg of
  radial deviation enabled by Anvil's wrist support bracket.
* **The wrist support bracket** — clamps the J6 rotor hub and lands on a
  plate bolted to the J7 motor end cap; represented in the MJCF by
  visual-only STL meshes from the hardware CAD, hosted on the ``link5``
  forearm bodies (the bracket must not rotate with J6).

Everything else — kinematics, meshes, native ``<position>`` actuators
with per-class PD gains, the single-driven-finger grippers with the
``<equality>``-coupled follower — is the upstream Enactic OpenArm v2.
The MJCF is generated by ``bensonlee5/anvil-openarm-mujoco`` (upstream
v2 files + the Anvil deltas, validated against the docs' numeric
comparison table) and fetched at a pinned SHA by
:mod:`openral_hal._anvil_openarm_v2_assets` via the
``openarm:anvil_v2_bimanual`` asset ref.

Like the Enactic v2 adapter (:mod:`openral_hal.openarm`) this is a thin
manifest-driven :class:`MujocoArmHAL` subclass (ADR-0023): the MJCF's
own PD law handles dynamics, ``send_action`` writes target → ctrl.

Action layout
-------------
16-DoF :class:`openral_core.Action`, same slot order as the Enactic
v2 adapter:

* ``target[0:7]``   — left arm joints (radians)
* ``target[7]``     — left gripper jaw (rad, ``[0, 0.7854]``)
* ``target[8:15]``  — right arm joints (radians)
* ``target[15]``    — right gripper jaw (rad, ``[-0.7854, 0]``)

Gripper ranges mirror in sign across the centreline exactly as on the
Enactic v2 arm.  J2 keeps the v2 mirrored asymmetry; J1 and J6 carry
the Anvil ranges (identical numerics on both arms — upstream encodes
the mirror as flipped axes).

Example:
    >>> from openral_hal import AnvilOpenArmV2MujocoHAL, ANVIL_OPENARM_V2_DESCRIPTION
    >>> hal = AnvilOpenArmV2MujocoHAL(gravity_enabled=False)  # doctest: +SKIP
    >>> hal.connect()  # doctest: +SKIP
    >>> state = hal.read_state()  # doctest: +SKIP
    >>> len(state.position) == len(ANVIL_OPENARM_V2_DESCRIPTION.joints) == 16  # doctest: +SKIP
    True
    >>> hal.disconnect()  # doctest: +SKIP
"""

from __future__ import annotations

from openral_core.schemas import (
    AssetRefs,
    ControlMode,
    EmbodimentKind,
    EndEffectorSpec,
    GripperReadMode,
    GripperWriteMode,
    HalEntrypoints,
    HalParameters,
    Hand,
    IntrinsicsPinhole,
    JointSpec,
    JointType,
    RobotCapabilities,
    RobotDescription,
    SafetyEnvelope,
    SensorModality,
    SensorSpec,
    SimDescription,
    SimGripperDescription,
)

from openral_hal._mujoco_arm import MujocoArmHAL

__all__ = ["ANVIL_OPENARM_V2_DESCRIPTION", "AnvilOpenArmV2MujocoHAL"]


# ── Joint inventory ──────────────────────────────────────────────────────────
# Same 16-DoF public surface as the Enactic v2 adapter: 7 arm + 1
# gripper per side, left then right.  Logical names drop the MJCF's
# ``openarm_`` prefix (carried in ``sim_joint_name``).

_ANVIL_LEFT_ARM_JOINTS: tuple[str, ...] = tuple(f"left_joint{i}" for i in range(1, 8))
_ANVIL_RIGHT_ARM_JOINTS: tuple[str, ...] = tuple(f"right_joint{i}" for i in range(1, 8))
_ANVIL_LEFT_GRIPPER_JOINT: str = "left_gripper"
_ANVIL_RIGHT_GRIPPER_JOINT: str = "right_gripper"


# ── Joint limits (Anvil OpenARM 2.0 docs comparison table; values
# verbatim from the generated MJCF) ──────────────────────────────────────────
# J1 (+/-135 deg, symmetric — the Anvil delta vs v2's mirrored
# -200..+80) and J6 (-45..+70 deg — the bracket-enabled delta vs v2's
# +/-45) carry identical numerics on both arms because upstream encodes
# the left/right mirror as flipped joint axes.  J2 keeps the v2
# mirrored asymmetry.

_ANVIL_LEFT_ARM_POSITION_LIMITS: dict[str, tuple[float, float]] = {
    "left_joint1": (-2.3562, 2.3562),  # Anvil: +/-135 deg
    "left_joint2": (-3.31613, 0.174533),
    "left_joint3": (-1.5708, 1.5708),
    "left_joint4": (0.0, 2.44346),
    "left_joint5": (-1.5708, 1.5708),
    "left_joint6": (-0.7854, 1.2217),  # Anvil: -45..+70 deg deviation
    "left_joint7": (-1.5708, 1.5708),
}
_ANVIL_RIGHT_ARM_POSITION_LIMITS: dict[str, tuple[float, float]] = {
    "right_joint1": (-2.3562, 2.3562),  # Anvil: +/-135 deg (no v2 mirror)
    "right_joint2": (-0.174533, 3.31613),  # mirrored (as v2)
    "right_joint3": (-1.5708, 1.5708),
    "right_joint4": (0.0, 2.44346),
    "right_joint5": (-1.5708, 1.5708),
    "right_joint6": (-0.7854, 1.2217),  # Anvil: -45..+70 deg deviation
    "right_joint7": (-1.5708, 1.5708),
}
# v2-style hinge grippers: left jaw positive, right jaw mirrored negative.
_ANVIL_LEFT_GRIPPER_POSITION_LIMITS: tuple[float, float] = (0.0, 0.7854)
_ANVIL_RIGHT_GRIPPER_POSITION_LIMITS: tuple[float, float] = (-0.7854, 0.0)


# Joint-level actuator force clamps (N·m) from the MJCF
# ``actuatorfrcrange`` — DM8009 / DM4340 / DM4310-class motors.
_ANVIL_ARM_EFFORT_LIMITS: dict[str, float] = {
    "left_joint1": 40.0,
    "left_joint2": 40.0,
    "left_joint3": 27.0,
    "left_joint4": 27.0,
    "left_joint5": 7.0,
    "left_joint6": 7.0,
    "left_joint7": 7.0,
    "right_joint1": 40.0,
    "right_joint2": 40.0,
    "right_joint3": 27.0,
    "right_joint4": 27.0,
    "right_joint5": 7.0,
    "right_joint6": 7.0,
    "right_joint7": 7.0,
}
_ANVIL_GRIPPER_EFFORT_LIMIT: float = 10.0  # finger joint actuatorfrcrange [-10, 10]

# Conservative velocity limits (half the published peak), matching the
# Enactic v2 manifest.
_ANVIL_ARM_VELOCITY_LIMIT: float = 4.0
_ANVIL_GRIPPER_VELOCITY_LIMIT: float = 4.0


def _anvil_arm_joint_specs(
    names: tuple[str, ...],
    position_limits: dict[str, tuple[float, float]],
    side: str,
) -> list[JointSpec]:
    # Body chain in the v2-era MJCF: base_link → link1..link6 → ee_base_link.
    parents = [f"openarm_{side}_base_link"] + [f"openarm_{side}_link{i}" for i in range(1, 7)]
    children = [f"openarm_{side}_link{i}" for i in range(1, 7)] + [f"openarm_{side}_ee_base_link"]
    return [
        JointSpec(
            name=name,
            joint_type=JointType.REVOLUTE,
            parent_link=parent,
            child_link=child,
            position_limits=position_limits[name],
            velocity_limit=_ANVIL_ARM_VELOCITY_LIMIT,
            effort_limit=_ANVIL_ARM_EFFORT_LIMITS[name],
            has_torque_sensor=True,
            actuator_kind="bldc",
            # The MJCF qualifies the logical joint with the ``openarm_``
            # prefix (must match robots/anvil_openarm_v2/robot.yaml).
            sim_joint_name=f"openarm_{name}",
        )
        for name, parent, child in zip(names, parents, children, strict=True)
    ]


def _anvil_gripper_joint_spec(
    name: str, side: str, position_limits: tuple[float, float]
) -> JointSpec:
    # The public gripper channel drives ``finger_joint1`` (the inner
    # finger); the outer finger follows via the MJCF ``<equality>``.
    return JointSpec(
        name=name,
        joint_type=JointType.REVOLUTE,  # v2-era grippers are hinge jaws
        parent_link=f"openarm_{side}_ee_base_link",
        child_link=f"openarm_{side}_ee_inner_finger",
        position_limits=position_limits,
        velocity_limit=_ANVIL_GRIPPER_VELOCITY_LIMIT,
        effort_limit=_ANVIL_GRIPPER_EFFORT_LIMIT,
        has_torque_sensor=False,
        actuator_kind="servo",
        role="gripper",
    )


def _anvil_joint_specs() -> list[JointSpec]:
    return [
        *_anvil_arm_joint_specs(_ANVIL_LEFT_ARM_JOINTS, _ANVIL_LEFT_ARM_POSITION_LIMITS, "left"),
        _anvil_gripper_joint_spec(
            _ANVIL_LEFT_GRIPPER_JOINT, "left", _ANVIL_LEFT_GRIPPER_POSITION_LIMITS
        ),
        *_anvil_arm_joint_specs(_ANVIL_RIGHT_ARM_JOINTS, _ANVIL_RIGHT_ARM_POSITION_LIMITS, "right"),
        _anvil_gripper_joint_spec(
            _ANVIL_RIGHT_GRIPPER_JOINT, "right", _ANVIL_RIGHT_GRIPPER_POSITION_LIMITS
        ),
    ]


# ── RobotDescription ─────────────────────────────────────────────────────────

ANVIL_OPENARM_V2_DESCRIPTION = RobotDescription(
    name="anvil_openarm_v2",
    embodiment_kind=EmbodimentKind.BIMANUAL,
    # The Anvil bimanual MJCF mounts both arm base_link bodies directly
    # in the worldbody (no shared torso body), so — like the ALOHA
    # MuJoCo-only manifest — the base frame is the world frame.
    base_frame="world",
    joints=_anvil_joint_specs(),
    end_effectors=[
        EndEffectorSpec(
            name="left_gripper",
            kind="parallel_gripper",
            hand=Hand.LEFT,
            n_dof=1,
            max_grip_force_n=_ANVIL_GRIPPER_EFFORT_LIMIT,
            max_payload_kg=2.0,
            workspace_radius_m=0.7,
        ),
        EndEffectorSpec(
            name="right_gripper",
            kind="parallel_gripper",
            hand=Hand.RIGHT,
            n_dof=1,
            max_grip_force_n=_ANVIL_GRIPPER_EFFORT_LIMIT,
            max_payload_kg=2.0,
            workspace_radius_m=0.7,
        ),
    ],
    # The Anvil bimanual MJCF ships two wrist cameras (fovy 66 deg,
    # 960x600 on the real rig).  The MJCF leaves MuJoCo's offscreen
    # framebuffer at its 640x480 default, so the sim sensors render at
    # 640x400 — same 16:10 aspect, fovy-matched intrinsics
    # (fy = 200 / tan(33 deg) ≈ 308).  Published by
    # MujocoArmHAL.read_images via the SimSensorBridge (ADR-0065/0070).
    sensors=[
        SensorSpec(
            name="wrist_left",
            modality=SensorModality.RGB,
            frame_id="openarm_left_ee_base_link",
            rate_hz=10.0,
            intrinsics=IntrinsicsPinhole(
                width=640, height=400, fx=308.0, fy=308.0, cx=320.0, cy=200.0
            ),
            encoding="rgb8",
            vla_feature_key="observation.images.wrist_left",
            vendor="sim",
            model="mujoco_wrist",
            sim_camera_name="camera_wrist_left",
        ),
        SensorSpec(
            name="wrist_right",
            modality=SensorModality.RGB,
            frame_id="openarm_right_ee_base_link",
            rate_hz=10.0,
            intrinsics=IntrinsicsPinhole(
                width=640, height=400, fx=308.0, fy=308.0, cx=320.0, cy=200.0
            ),
            encoding="rgb8",
            vla_feature_key="observation.images.wrist_right",
            vendor="sim",
            model="mujoco_wrist",
            sim_camera_name="camera_wrist_right",
        ),
    ],
    capabilities=RobotCapabilities(
        can_lift_kg=2.0,
        has_force_control=True,
        has_vision=True,
        bimanual=True,
        supported_control_modes=[ControlMode.JOINT_POSITION],
        supported_vla_embodiments=["anvil_openarm_v2", "openarm"],
        embodiment_tags=["openarm", "anvil_openarm_v2", "anvil", "bimanual"],
    ),
    safety=SafetyEnvelope(
        max_ee_speed_m_s=1.0,
        max_joint_speed_factor=0.5,
        max_force_n=40.0,
        max_torque_nm=40.0,
        deadman_required=True,
    ),
    sdk_kind="open",
    hal=HalEntrypoints(
        sim="openral_hal.anvil_openarm_v2:AnvilOpenArmV2MujocoHAL",
        real=None,
        # Same manifest-driven construction defaults as the Enactic v2
        # arm; threaded by build_hal (ADR-0029).
        parameters=HalParameters(
            defaults={"settle_steps": 4, "gravity_enabled": False, "staleness_limit_s": 0.5}
        ),
    ),
    # MuJoCo wiring — the Anvil 2.0 bimanual MJCF fetched at a pinned
    # SHA by ``ensure_anvil_openarm_v2_mjcf`` (``openarm:anvil_v2_bimanual``).
    # No vendored URDF: upstream is xacro-only and, like ALOHA, the
    # MuJoCo asset is the sim source of truth (ADR-0027 / ADR-0058).
    #
    # qpos layout (18 slots, same as the Enactic v2 arm): left arm 0-6,
    # left fingers 7 + 8, right arm 9-15, right fingers 16 + 17.  The
    # public 16-DoF surface maps each gripper channel to finger_joint1
    # (qpos 7 / 16) and skips the <equality>-coupled follower (8 / 17).
    # 16 actuators in description.joints order → the default 1:1
    # actuator map is correct.  ``seed_ctrl_from_qpos=True`` because the
    # native <position> actuators would otherwise yank every joint to
    # ctrl=0 on the first mj_step.
    assets=AssetRefs(
        urdf=None,
        mjcf="openarm:anvil_v2_bimanual",
    ),
    sim=SimDescription(
        joint_qpos_addr={
            "left_joint1": 0,
            "left_joint2": 1,
            "left_joint3": 2,
            "left_joint4": 3,
            "left_joint5": 4,
            "left_joint6": 5,
            "left_joint7": 6,
            "left_gripper": 7,
            "right_joint1": 9,
            "right_joint2": 10,
            "right_joint3": 11,
            "right_joint4": 12,
            "right_joint5": 13,
            "right_joint6": 14,
            "right_joint7": 15,
            "right_gripper": 16,
        },
        grippers=[
            SimGripperDescription(
                joint="left_gripper",
                ctrl_range=(0.0, 0.7854),
                qpos_addrs=(7,),
                qpos_scale=0.7854,
                read_mode=GripperReadMode.PASSTHROUGH,
                write_mode=GripperWriteMode.PASSTHROUGH,
            ),
            SimGripperDescription(
                joint="right_gripper",
                ctrl_range=(-0.7854, 0.0),
                qpos_addrs=(16,),
                qpos_scale=0.7854,
                read_mode=GripperReadMode.PASSTHROUGH,
                write_mode=GripperWriteMode.PASSTHROUGH,
            ),
        ],
        seed_ctrl_from_qpos=True,
    ),
)


# ── HAL ──────────────────────────────────────────────────────────────────────


class AnvilOpenArmV2MujocoHAL(MujocoArmHAL):
    """HAL adapter for the Anvil OpenARM 2.0 (MuJoCo digital twin).

    Thin manifest-driven wrapper around :class:`MujocoArmHAL`, exactly
    like the Enactic v2 adapter: the MJCF ships native ``<position>``
    actuators with per-class PD gains, so all wiring (the
    ``openarm:anvil_v2_bimanual`` MJCF ref, the joint→qpos map that skips
    the follower fingers, two ``PASSTHROUGH`` hinge grippers,
    ``seed_ctrl_from_qpos``) lives in
    :data:`ANVIL_OPENARM_V2_DESCRIPTION.sim` (ADR-0023).

    What makes it the *Anvil* 2.0 rather than the stock v2 arm is
    entirely in the fetched MJCF: J1 clamped to +/-135 deg, J6 widened
    to -45..+70 deg of radial deviation, and the wrist support bracket
    (visual-only) that enables it — see
    :mod:`openral_hal._anvil_openarm_v2_assets`.

    Args:
        mjcf_path: Optional override for the MJCF file path.  When
            ``None``, the Anvil 2.0 bimanual MJCF is fetched lazily
            through ``ensure_anvil_openarm_v2_mjcf`` via the
            ``openarm:anvil_v2_bimanual`` URI scheme.
        settle_steps: Number of MuJoCo physics steps performed in
            :meth:`send_action`.
        gravity_enabled: When ``False``, gravity is zeroed at
            ``connect()`` time for deterministic closed-loop tests.
        staleness_limit_s: Maximum age of a cached state.

    Example:
        >>> from openral_hal import AnvilOpenArmV2MujocoHAL  # doctest: +SKIP
        >>> hal = AnvilOpenArmV2MujocoHAL(gravity_enabled=False)  # doctest: +SKIP
        >>> hal.connect()  # doctest: +SKIP
        >>> state = hal.read_state()  # doctest: +SKIP
        >>> len(state.position)  # 7 + 1 + 7 + 1  # doctest: +SKIP
        16
        >>> hal.disconnect()  # doctest: +SKIP
    """

    def __init__(
        self,
        *,
        mjcf_path: str | None = None,
        settle_steps: int = 1,
        gravity_enabled: bool = True,
        staleness_limit_s: float = 0.5,
    ) -> None:
        """Initialise the adapter; the MJCF is not loaded until ``connect()``."""
        self._init_from_description(
            ANVIL_OPENARM_V2_DESCRIPTION,
            mjcf_path=mjcf_path,
            settle_steps=settle_steps,
            gravity_enabled=gravity_enabled,
            staleness_limit_s=staleness_limit_s,
        )
