"""Byte-identical lowering regression — the standardized-description-asset
resolver's §5 safety gate (hard gate).

The C++ safety kernel checks self-collision (ACM) and world-collision against the
*lowered* ``collision_geometry`` + ``allowed_collision_pairs`` committed in each
``robot.yaml`` (part of the geometric safety collision-checking system). The
standardized-description-asset resolver change moves only *how the source files
are located*, never the geometry — so re-lowering every robot through the
provenance-correct dispatcher (:func:`openral_safety.urdf_lowering.lower_robot_auto`)
MUST reproduce the committed values exactly. A drift is a release blocker
(CLAUDE.md §3): it would change what the kernel checks without a paper trail.

This is the concrete mitigation the hazard-log entry references. It
exercises real manifests, real URDF/SRDF/MJCF assets, and the real lowering math
— no mocks, no stubs (§1.11). The committed manifest carries geometry rendered to
4 dp (``render_blocks``); the comparison is at that committed precision (rounded,
then ``tol=1e-6``), because that is exactly what the kernel loads. The math is
*not* loosened: a real change to the lowering algorithm shifts the 4 dp value and
fails the test. As a second, independent proof, the rendered blocks are asserted
byte-for-byte identical to the committed manifest's own rendered blocks.
"""

from __future__ import annotations

from pathlib import Path

import pytest
import yaml

pytest.importorskip("yourdfpy")
pytest.importorskip("mujoco")
pytest.importorskip("trimesh")
pytest.importorskip("robot_descriptions")

from openral_cli.collision import render_blocks
from openral_core import RobotDescription
from openral_core.schemas import CapsuleShape, LinkCollisionGeometry
from openral_safety.urdf_lowering import LoweredCollisionModel, lower_robot_auto, select_lowering

# Every committed robot manifest; the test skips those without collision geometry.
ROBOTS = sorted(Path("robots").glob("*/robot.yaml"))

# ── Known pre-existing drift: HAND-AUTHORED geometry no lowering path reproduces ─
#
# panda_mobile is the one robot whose committed ``collision_geometry`` is
# HAND-AUTHORED, not tool-generated: its block carries a hand "# Validated:
# manifest FK matches the live robosuite model…" comment instead of the
# "# GENERATED by `openral collision lower`" header every other robot has, and
# its capsules are clean round numbers (link5 = sphere r=0.060 at the origin;
# link7 r=0.060 L=0.100) rather than PCA-fitted ones. The committed ACM was then
# generated against THAT hand geometry, so it carries the always-colliding
# ``panda_link5 ↔ panda_link7`` capsule-junction pair (the short link6 makes the
# hand-tuned link5/link7 capsules overlap in every pose).
#
# Re-lowering panda_mobile through ANY current path drifts: it has an SRDF + a
# ``rd:panda_description`` URDF but NO MJCF, so the only routes are the SRDF /
# sampling URDF paths — both FIT geometry from the URDF meshes, producing
# different capsules (link5 r≈0.094 L≈0.347, tilted), under which link5/link7 no
# longer always-collide, so the ACM loses that pair. This drift is NOT introduced
# by the standardized-description-asset resolver change (the old
# ``lower_robot``-for-everything CLI
# drifted it identically); it is a pre-existing condition the fleet-wide
# regression now surfaces.
#
# DECISION (standardized-description-asset resolver §5, recorded 2026-06-16):
# KEEP the hand-authored geometry.
# A deliberate candidate re-lower was performed and REJECTED — it is not
# at-least-as-conservative (CLAUDE.md §3): it shrinks link7's capsule
# (radius 0.060 → 0.053 m, a smaller collision envelope) and drops the hand-tuned
# ``panda_link5 ↔ panda_link7`` ACM exception, which would re-introduce the
# spurious E-stop that exception was added to prevent (links 5/7 sit folded
# together in the stowed config). The hand geometry is therefore AUTHORITATIVE.
# This entry is an accepted, deliberately-not-auto-reproducible exception, not a
# pending fix. Kept strict-xfail so it stays LOUD: if a future change makes the
# auto-lowering reproduce the hand geometry, the strict marker fails and forces
# revisiting this decision.
#
# Detected structurally (not by a hard-coded name) the same way the fleet guard
# tests/unit/test_collision_lowering_fleet.py does: a tool-generated geometry
# block carries a "# GENERATED" header on the line directly above
# ``collision_geometry:``; a hand-authored one does not. (openarm also lacks the
# header but its MJCF path keeps the manifest geometry verbatim, so it still
# re-lowers byte-identically and is NOT a drift.)


def _has_generated_geometry_header(manifest: Path) -> bool:
    """True iff ``collision_geometry:`` is preceded by the tool's GENERATED header."""
    lines = manifest.read_text(encoding="utf-8").splitlines()
    idx = next((i for i, ln in enumerate(lines) if ln.startswith("collision_geometry:")), None)
    return idx is not None and idx > 0 and lines[idx - 1].startswith("# GENERATED")


def _is_known_hand_authored_drift(manifest: Path) -> bool:
    """Hand-authored geometry (no GENERATED header) that no current path re-lowers.

    openarm also lacks the header, but its MJCF lowering keeps the manifest
    capsules verbatim, so it reproduces byte-identically — only robots WITHOUT an
    MJCF-native keep path (panda_mobile today) genuinely drift.
    """
    desc = RobotDescription.model_validate(yaml.safe_load(manifest.read_text()))
    if _has_generated_geometry_header(manifest):
        return False
    # A robot that lowers from MJCF keeps its manifest geometry verbatim → no drift.
    return bool(select_lowering(desc, manifest_dir=manifest.parent) != "mjcf")


# The committed manifests render geometry to 4 dp (openral_cli.collision.render_blocks),
# so the kernel loads 4-dp values. Compare relowered floats at that committed
# precision: round to 4 dp, then assert equal within a tight numeric tolerance.
# This is NOT a loosened tolerance — it is the precision the manifest actually
# carries. A genuine change in the lowering math shifts the 4-dp value and fails.
_RENDER_DP = 4
_TOL = 1e-6


def _round(v: float) -> float:
    return round(v, _RENDER_DP)


def _geom_scalars(g: LinkCollisionGeometry) -> tuple[float, ...]:
    """A link's numeric capsule/sphere params at committed (4-dp) precision.

    radius, then half-length (0.0 for a sphere — it carries no ``length_m``),
    then the 6-DoF origin (xyz + rpy). The shape kind and link name are compared
    separately (exact, not numeric).
    """
    radius = _round(g.shape.radius_m)
    length = _round(g.shape.length_m) if isinstance(g.shape, CapsuleShape) else 0.0
    return (radius, length, *(_round(x) for x in g.origin_xyz_rpy))


def _geom_equal(
    relowered: list[LinkCollisionGeometry],
    committed: list[LinkCollisionGeometry],
    *,
    tol: float = _TOL,
) -> bool:
    """True iff the two per-link geometries match at committed precision within ``tol``.

    Compares per link: shape kind, radius, half-length (capsule), and the 6-DoF
    origin (xyz + rpy). The lists must cover the same link set and the same length
    — a missing or extra link is a drift, never silently ignored.
    """
    if len(relowered) != len(committed):
        return False
    rel = {g.link_name: g for g in relowered}
    com = {g.link_name: g for g in committed}
    if set(rel) != set(com):
        return False
    for link_name, b in com.items():
        a = rel[link_name]
        if a.shape.shape != b.shape.shape:
            return False
        if any(abs(x - y) > tol for x, y in zip(_geom_scalars(a), _geom_scalars(b), strict=True)):
            return False
    return True


def _acm_as_pairs(pairs: list[tuple[str, str]]) -> set[frozenset[str]]:
    """ACM as a set of unordered link pairs (order-insensitive equality)."""
    return {frozenset(p) for p in pairs}


def _param(manifest: Path) -> object:
    """Parametrize a manifest, strict-xfail'ing any known hand-authored drift.

    Robots without committed collision geometry can't be probed for the drift
    condition (and the test skips them anyway), so only probe those that have it.
    """
    name = manifest.parent.name
    has_geom = "collision_geometry:" in manifest.read_text(encoding="utf-8")
    if has_geom and _is_known_hand_authored_drift(manifest):
        return pytest.param(
            manifest,
            id=name,
            marks=pytest.mark.xfail(
                strict=True,
                reason=(
                    f"{name} collision_geometry is HAND-AUTHORED (no GENERATED "
                    "header) and has no MJCF-native keep path; no current lowering "
                    "path reproduces it. Needs a deliberate re-lower + safety-WG "
                    "sign-off (standardized-description-asset resolver §5) — "
                    "a human gate, not an automated "
                    "routing fix."
                ),
            ),
        )
    return pytest.param(manifest, id=name)


@pytest.mark.parametrize("manifest", [_param(p) for p in ROBOTS])
def test_lowering_output_unchanged(manifest: Path) -> None:
    """Re-lowering a robot reproduces its committed collision model exactly
    (via the standardized-description-asset resolver)."""
    desc = RobotDescription.model_validate(yaml.safe_load(manifest.read_text()))
    if not desc.collision_geometry:
        pytest.skip("no collision_geometry to regress")

    relowered = lower_robot_auto(desc, manifest_dir=manifest.parent)

    # 1. Routing picks the provenance-correct source (no silent source flip).
    committed_source = relowered.acm_source
    assert select_lowering(desc, manifest_dir=manifest.parent) == committed_source

    # 2. ACM pairs: exact set equality (byte-for-byte once sorted/rendered).
    assert _acm_as_pairs(relowered.allowed_collision_pairs) == _acm_as_pairs(
        desc.allowed_collision_pairs
    ), f"{manifest.parent.name}: ACM drifted"
    # The lowering emits a deterministic sorted list; assert the exact order too.
    assert relowered.allowed_collision_pairs == desc.allowed_collision_pairs, (
        f"{manifest.parent.name}: ACM pair order drifted"
    )

    # 3. Geometry: per-link capsule/sphere equal at committed precision (tol=1e-6).
    assert _geom_equal(relowered.collision_geometry, list(desc.collision_geometry), tol=_TOL), (
        f"{manifest.parent.name}: collision_geometry drifted"
    )

    # 4. Independent byte-identical proof: the rendered blocks (what gets committed
    #    and what the kernel ultimately loads) are string-identical.
    committed_model = LoweredCollisionModel(
        collision_geometry=list(desc.collision_geometry),
        allowed_collision_pairs=list(desc.allowed_collision_pairs),
        acm_source=relowered.acm_source,
    )
    rel_geo, rel_acm = render_blocks(relowered)
    com_geo, com_acm = render_blocks(committed_model)
    assert rel_geo == com_geo, f"{manifest.parent.name}: rendered geometry block drifted"
    assert rel_acm == com_acm, f"{manifest.parent.name}: rendered ACM block drifted"
