"""Unit tests for the rSkill README + manifest documentation validator.

Pins the publish-gate contract for ``tools/rskill_publisher.py``:

* A missing / too-short / sentinel-laden README blocks publishing.
* A manifest with the template's ``"Scaffold template generated by …"``
  description blocks publishing.
* A manifest with neither ``paper_url`` nor ``source_repo`` blocks publishing.
* A ``TEMPLATE_ORG`` / ``TEMPLATE_ID`` substring anywhere in the manifest
  blocks publishing.
* Every in-tree rSkill (sans the template scaffold itself) passes the
  validator — regression guard so a new gate doesn't quietly break a
  shipped skill.

No mocks: tests build real ``RSkillManifest`` instances from YAML
fixtures written to ``tmp_path`` and call the validator against real
files (CLAUDE.md §1.11). The in-tree regression test reads the actual
``rskills/*/README.md`` and ``rskills/*/rskill.yaml`` from the repo.
"""

from __future__ import annotations

import textwrap
from pathlib import Path

import pytest
from openral_cli._rskill_doc_validator import (
    DELEGATION_MARKER_NAME,
    PLACEHOLDER_MANIFEST_DESCRIPTION_MARKERS,
    DocValidationReport,
    format_report,
    validate_rskill_docs,
)
from openral_core.schemas import RSkillManifest

# ── Test fixtures ────────────────────────────────────────────────────────────

_VALID_MANIFEST_YAML = textwrap.dedent("""\
    name: test/rskill-doc-fixture
    version: "0.1.0"
    license: apache-2.0
    role: s1
    kind: vla
    model_family: smolvla
    embodiment_tags: [so100_follower]
    runtime: pytorch
    weights_uri: "hf://test/doc-fixture"
    chunk_size: 16
    latency_budget:
      per_chunk_ms: 100.0
    actuators_required:
      - kind: joint_position
        control_mode_semantics: {mode: absolute}
    processors:
      preprocessor_uri: "hf://test/doc-fixture/policy_preprocessor.json"
      postprocessor_uri: "hf://test/doc-fixture/policy_postprocessor.json"
    paper_url: "https://arxiv.org/abs/9999.99999"
    source_repo: "hf://test/doc-fixture"
    description: "Picks a cube from the tabletop on the SO-100 follower arm."
    actions:
      - pick
    objects:
      - cube
    scenes:
      - tabletop
""")

_GOOD_README = textwrap.dedent("""\
    # rskill-doc-fixture

    > **OpenRAL rSkill** — pick a cube on the SO-100 follower arm.
    > Real package, real README, fully filled in.

    ## Preview

    ![demo](media/demo.png)

    ## Upstream model

    Wraps the upstream Apache-2.0 checkpoint. Paper: SmolVLA (arxiv:2506.01844).
    Trained on the LIBERO benchmark with ~1700 demonstrations.

    ## Supported robots

    | Robot | Embodiment tag | Status |
    | --- | --- | --- |
    | SO-100 follower | so100_follower | ✓ validated |

    ## Sensors required

    | Key | Modality | Resolution |
    | --- | --- | --- |
    | observation.images.camera1 | RGB | 224 × 224 |
    | observation.images.camera2 | RGB | 224 × 224 |

    ## Manifest summary

    See `rskill.yaml` for the full set of fields.

    ## License

    Apache-2.0, matching the wrapped upstream weights.
""")


def _write_skill_dir(
    base: Path,
    *,
    manifest_yaml: str = _VALID_MANIFEST_YAML,
    readme: str | None = _GOOD_README,
) -> tuple[Path, RSkillManifest]:
    """Create a real rSkill directory under ``base`` and return (dir, manifest).

    Args:
        base: The parent directory (typically a pytest ``tmp_path``).
        manifest_yaml: YAML body to write as ``rskill.yaml``.
        readme: README body to write, or ``None`` to skip the README.
    """
    skill_dir = base / "rskill-doc-fixture"
    skill_dir.mkdir(parents=True)
    (skill_dir / "rskill.yaml").write_text(manifest_yaml, encoding="utf-8")
    if readme is not None:
        (skill_dir / "README.md").write_text(readme, encoding="utf-8")
    manifest = RSkillManifest.from_yaml(str(skill_dir / "rskill.yaml"))
    return skill_dir, manifest


# ── Happy path ──────────────────────────────────────────────────────────────


def test_valid_rskill_passes(tmp_path: Path) -> None:
    """A real manifest + a fleshed-out README → no errors."""
    skill_dir, manifest = _write_skill_dir(tmp_path)
    report = validate_rskill_docs(skill_dir, manifest)
    assert report.is_valid, report.errors
    assert report.errors == []


def test_report_carries_manifest_name(tmp_path: Path) -> None:
    skill_dir, manifest = _write_skill_dir(tmp_path)
    report = validate_rskill_docs(skill_dir, manifest)
    assert report.manifest_name == "test/rskill-doc-fixture"
    assert report.skill_dir.endswith("rskill-doc-fixture")


# ── README failure modes ─────────────────────────────────────────────────────


def test_missing_readme_blocks_publish(tmp_path: Path) -> None:
    skill_dir, manifest = _write_skill_dir(tmp_path, readme=None)
    report = validate_rskill_docs(skill_dir, manifest)
    assert not report.is_valid
    fields = {i.field for i in report.errors}
    assert "readme" in fields


def test_short_readme_blocks_publish(tmp_path: Path) -> None:
    skill_dir, manifest = _write_skill_dir(tmp_path, readme="# tiny\n")
    report = validate_rskill_docs(skill_dir, manifest)
    assert not report.is_valid
    assert any(i.field == "readme.body" for i in report.errors)


def test_readme_missing_license_section_blocks_publish(tmp_path: Path) -> None:
    readme = _GOOD_README.replace("## License", "## Legalese-ish")
    # The substring "license" doesn't appear in any heading now; section fails.
    # Note: "license" might still appear in the body (it does), but the
    # validator scans headings only — that's the point.
    readme_clean = readme.replace("Apache-2.0, matching the wrapped upstream weights.", "")
    skill_dir, manifest = _write_skill_dir(tmp_path, readme=readme_clean)
    report = validate_rskill_docs(skill_dir, manifest)
    assert not report.is_valid
    license_errors = [i for i in report.errors if "license" in i.field.lower()]
    assert license_errors, f"expected a license section error, got {report.errors}"


def test_readme_missing_robots_section_blocks_publish(tmp_path: Path) -> None:
    readme = _GOOD_README.replace("## Supported robots", "## Compatibility")
    # "compatibility" doesn't match any of robot/embodiment/supported,
    # but "Supported robots" did. With it renamed, the section is missing.
    skill_dir, manifest = _write_skill_dir(tmp_path, readme=readme)
    report = validate_rskill_docs(skill_dir, manifest)
    # Note: "supported" is still in the substring list; we have to make sure
    # neither "robot" nor "embodiment" nor "supported" survives anywhere.
    # The README still says "Sensors required" → "supported" not present.
    # The README still says nothing about "robot" / "embodiment".
    assert not report.is_valid
    robot_errors = [
        i for i in report.errors if "robot" in i.field.lower() or "embodiment" in i.field.lower()
    ]
    assert robot_errors, f"expected a robots section error, got {report.errors}"


def test_readme_with_template_sentinel_blocks_publish(tmp_path: Path) -> None:
    readme = _GOOD_README + "\n\nUpload at hf://TEMPLATE_ORG/TEMPLATE_ID\n"
    skill_dir, manifest = _write_skill_dir(tmp_path, readme=readme)
    report = validate_rskill_docs(skill_dir, manifest)
    assert not report.is_valid
    placeholder_errors = [i for i in report.errors if i.field == "readme.placeholder"]
    assert placeholder_errors


def test_readme_with_todo_sentinel_blocks_publish(tmp_path: Path) -> None:
    readme = _GOOD_README + "\n\nTODO: write the architecture paragraph\n"
    skill_dir, manifest = _write_skill_dir(tmp_path, readme=readme)
    report = validate_rskill_docs(skill_dir, manifest)
    assert not report.is_valid
    assert any(i.field == "readme.placeholder" for i in report.errors)


def test_readme_without_media_warns_but_still_publishes(tmp_path: Path) -> None:
    """No image/video -> a `readme.media` warning, not a publish-blocking error."""
    readme = _GOOD_README.replace("![demo](media/demo.png)", "")
    skill_dir, manifest = _write_skill_dir(tmp_path, readme=readme)
    report = validate_rskill_docs(skill_dir, manifest)
    assert report.is_valid  # warning only, no error
    media_warnings = [i for i in report.warnings if i.field == "readme.media"]
    assert media_warnings, "expected a readme.media warning when no image/video present"


def test_readme_with_video_tag_satisfies_media(tmp_path: Path) -> None:
    """An HTML5 <video> tag counts as media (no warning)."""
    readme = _GOOD_README.replace("![demo](media/demo.png)", '<video src="media/demo.mp4"></video>')
    skill_dir, manifest = _write_skill_dir(tmp_path, readme=readme)
    report = validate_rskill_docs(skill_dir, manifest)
    assert not [i for i in report.warnings if i.field == "readme.media"]


# ── Manifest failure modes ───────────────────────────────────────────────────


def test_template_description_blocks_publish(tmp_path: Path) -> None:
    bad_yaml = _VALID_MANIFEST_YAML.replace(
        'description: "Picks a cube from the tabletop on the SO-100 follower arm."',
        (
            'description: "Scaffold template generated by ral skill new. '
            'Edit this description before publishing."'
        ),
    )
    skill_dir, manifest = _write_skill_dir(tmp_path, manifest_yaml=bad_yaml)
    report = validate_rskill_docs(skill_dir, manifest)
    assert not report.is_valid
    assert any(i.field == "manifest.description" for i in report.errors)


def test_every_placeholder_marker_in_description_is_caught(tmp_path: Path) -> None:
    """Each marker in :data:`PLACEHOLDER_MANIFEST_DESCRIPTION_MARKERS` is detected."""
    for marker in PLACEHOLDER_MANIFEST_DESCRIPTION_MARKERS:
        description = f"{marker} — example padding to clear the min-length bar."
        yaml_body = _VALID_MANIFEST_YAML.replace(
            'description: "Picks a cube from the tabletop on the SO-100 follower arm."',
            f'description: "{description}"',
        )
        # Use a unique subdir per iteration so file writes don't collide.
        sub = tmp_path / marker.replace(" ", "_").replace(":", "")
        sub.mkdir()
        skill_dir, manifest = _write_skill_dir(sub, manifest_yaml=yaml_body)
        report = validate_rskill_docs(skill_dir, manifest)
        assert not report.is_valid, f"marker {marker!r} should trigger a doc error"


def test_short_description_blocks_publish(tmp_path: Path) -> None:
    yaml_body = _VALID_MANIFEST_YAML.replace(
        'description: "Picks a cube from the tabletop on the SO-100 follower arm."',
        'description: "Picks a cube."',  # 13 chars, below MIN_DESCRIPTION_LENGTH=30
    )
    skill_dir, manifest = _write_skill_dir(tmp_path, manifest_yaml=yaml_body)
    report = validate_rskill_docs(skill_dir, manifest)
    assert not report.is_valid
    desc_errors = [i for i in report.errors if i.field == "manifest.description"]
    assert desc_errors


def test_missing_paper_url_and_source_repo_blocks_publish(tmp_path: Path) -> None:
    """Removing both provenance fields trips the publish gate."""
    yaml_body = _VALID_MANIFEST_YAML
    yaml_body = yaml_body.replace('paper_url: "https://arxiv.org/abs/9999.99999"\n', "")
    yaml_body = yaml_body.replace('source_repo: "hf://test/doc-fixture"\n', "")
    skill_dir, manifest = _write_skill_dir(tmp_path, manifest_yaml=yaml_body)
    report = validate_rskill_docs(skill_dir, manifest)
    assert not report.is_valid
    assert any(i.field == "manifest.provenance" for i in report.errors)


def test_paper_url_alone_is_sufficient_provenance(tmp_path: Path) -> None:
    yaml_body = _VALID_MANIFEST_YAML.replace('source_repo: "hf://test/doc-fixture"\n', "")
    skill_dir, manifest = _write_skill_dir(tmp_path, manifest_yaml=yaml_body)
    report = validate_rskill_docs(skill_dir, manifest)
    assert report.is_valid, report.errors


def test_source_repo_alone_is_sufficient_provenance(tmp_path: Path) -> None:
    yaml_body = _VALID_MANIFEST_YAML.replace('paper_url: "https://arxiv.org/abs/9999.99999"\n', "")
    skill_dir, manifest = _write_skill_dir(tmp_path, manifest_yaml=yaml_body)
    report = validate_rskill_docs(skill_dir, manifest)
    assert report.is_valid, report.errors


def test_template_substring_in_weights_uri_blocks_publish(tmp_path: Path) -> None:
    yaml_body = _VALID_MANIFEST_YAML.replace(
        'weights_uri: "hf://test/doc-fixture"',
        'weights_uri: "hf://TEMPLATE_ORG/TEMPLATE_ID"',
    )
    skill_dir, manifest = _write_skill_dir(tmp_path, manifest_yaml=yaml_body)
    report = validate_rskill_docs(skill_dir, manifest)
    assert not report.is_valid
    assert any(i.field == "manifest.weights_uri" for i in report.errors)


def test_template_substring_in_source_repo_blocks_publish(tmp_path: Path) -> None:
    yaml_body = _VALID_MANIFEST_YAML.replace(
        'source_repo: "hf://test/doc-fixture"',
        'source_repo: "hf://TEMPLATE_ORG/TEMPLATE_ID"',
    )
    skill_dir, manifest = _write_skill_dir(tmp_path, manifest_yaml=yaml_body)
    report = validate_rskill_docs(skill_dir, manifest)
    assert not report.is_valid
    assert any(i.field == "manifest.source_repo" for i in report.errors)


# ── format_report ───────────────────────────────────────────────────────────


def test_format_report_valid_skill(tmp_path: Path) -> None:
    skill_dir, manifest = _write_skill_dir(tmp_path)
    report = validate_rskill_docs(skill_dir, manifest)
    rendered = format_report(report)
    assert "publish-ready" in rendered
    assert report.manifest_name in rendered


def test_format_report_invalid_skill(tmp_path: Path) -> None:
    skill_dir, manifest = _write_skill_dir(tmp_path, readme=None)
    report = validate_rskill_docs(skill_dir, manifest)
    rendered = format_report(report)
    assert "error:" in rendered
    assert "BLOCKED" in rendered


def test_format_report_isvalid_property(tmp_path: Path) -> None:
    skill_dir, manifest = _write_skill_dir(tmp_path)
    good_report = validate_rskill_docs(skill_dir, manifest)
    assert isinstance(good_report, DocValidationReport)
    assert good_report.is_valid is True
    assert good_report.errors == []

    bad_skill_dir, bad_manifest = _write_skill_dir(tmp_path / "broken", readme=None)
    bad_report = validate_rskill_docs(bad_skill_dir, bad_manifest)
    assert bad_report.is_valid is False
    assert len(bad_report.errors) >= 1


# ── Delegation ──────────────────────────────────────────────────────────────


def test_delegation_to_a_real_sibling_passes(tmp_path: Path) -> None:
    """A stub README that delegates to a sibling with all sections passes."""
    # Build the canonical sibling first.
    sibling_dir, sibling_manifest = _write_skill_dir(
        tmp_path / "canonical",
        manifest_yaml=_VALID_MANIFEST_YAML.replace(
            "test/rskill-doc-fixture", "test/rskill-canonical"
        ),
    )
    sibling_report = validate_rskill_docs(sibling_dir, sibling_manifest)
    assert sibling_report.is_valid

    # Now a stub that delegates.
    stub_dir = tmp_path / "stub" / "rskill-stub"
    stub_dir.mkdir(parents=True)
    (stub_dir / "rskill.yaml").write_text(
        _VALID_MANIFEST_YAML.replace("test/rskill-doc-fixture", "test/rskill-stub"),
        encoding="utf-8",
    )
    stub_readme = textwrap.dedent(f"""\
        # rskill-stub

        > A short variant that delegates to its canonical sibling.

        <!-- {DELEGATION_MARKER_NAME}: {sibling_dir} -->

        See the sibling README for shared architecture / license / sensors.

        Upstream: <https://huggingface.co/example/stub>
    """)
    (stub_dir / "README.md").write_text(stub_readme, encoding="utf-8")
    stub_manifest = RSkillManifest.from_yaml(str(stub_dir / "rskill.yaml"))
    report = validate_rskill_docs(stub_dir, stub_manifest)
    assert report.is_valid, report.errors


def test_delegation_to_missing_sibling_blocks_publish(tmp_path: Path) -> None:
    stub_dir, manifest = _write_skill_dir(
        tmp_path,
        readme=textwrap.dedent(f"""\
            # rskill-stub
            > Stub with a broken delegation marker.

            <!-- {DELEGATION_MARKER_NAME}: ./does-not-exist -->

            Upstream: <https://huggingface.co/example/stub>
        """),
    )
    report = validate_rskill_docs(stub_dir, manifest)
    assert not report.is_valid
    assert any(i.field == "readme.delegation" for i in report.errors)


def test_double_hop_delegation_is_rejected(tmp_path: Path) -> None:
    """A delegated-to README cannot itself delegate further."""
    # canonical → has full sections (so first hop "passes" sections)
    canonical_dir, _ = _write_skill_dir(
        tmp_path / "canonical",
        manifest_yaml=_VALID_MANIFEST_YAML.replace(
            "test/rskill-doc-fixture", "test/rskill-canonical"
        ),
    )

    # middle → delegates to canonical, but has the marker itself
    middle_dir = tmp_path / "middle" / "rskill-middle"
    middle_dir.mkdir(parents=True)
    middle_readme = textwrap.dedent(f"""\
        # rskill-middle
        > Middle stub.

        <!-- {DELEGATION_MARKER_NAME}: {canonical_dir} -->

        Padding text to clear the min-body length so the failure is
        the double-hop marker, not the short-body check.
        Upstream: <https://huggingface.co/example/middle>
    """)
    (middle_dir / "README.md").write_text(middle_readme, encoding="utf-8")
    (middle_dir / "rskill.yaml").write_text(
        _VALID_MANIFEST_YAML.replace("test/rskill-doc-fixture", "test/rskill-middle"),
        encoding="utf-8",
    )

    # top → delegates to middle (which itself delegates → should fail)
    top_dir = tmp_path / "top" / "rskill-top"
    top_dir.mkdir(parents=True)
    top_readme = textwrap.dedent(f"""\
        # rskill-top
        > Top of the chain.

        <!-- {DELEGATION_MARKER_NAME}: {middle_dir} -->

        Padding text to clear the min-body length so the failure is the
        double-hop marker, not the short-body check.
        Upstream: <https://huggingface.co/example/top>
    """)
    (top_dir / "README.md").write_text(top_readme, encoding="utf-8")
    (top_dir / "rskill.yaml").write_text(
        _VALID_MANIFEST_YAML.replace("test/rskill-doc-fixture", "test/rskill-top"),
        encoding="utf-8",
    )

    manifest = RSkillManifest.from_yaml(str(top_dir / "rskill.yaml"))
    report = validate_rskill_docs(top_dir, manifest)
    assert not report.is_valid
    delegation_errors = [i for i in report.errors if i.field == "readme.delegation"]
    assert delegation_errors


def test_delegation_still_enforces_placeholder_check(tmp_path: Path) -> None:
    """A delegating stub README must not contain template sentinels itself."""
    canonical_dir, _ = _write_skill_dir(
        tmp_path / "canonical",
        manifest_yaml=_VALID_MANIFEST_YAML.replace(
            "test/rskill-doc-fixture", "test/rskill-canonical"
        ),
    )
    stub_dir = tmp_path / "stub" / "rskill-stub"
    stub_dir.mkdir(parents=True)
    (stub_dir / "rskill.yaml").write_text(
        _VALID_MANIFEST_YAML.replace("test/rskill-doc-fixture", "test/rskill-stub"),
        encoding="utf-8",
    )
    # Stub README delegates but also still contains a TODO: sentinel.
    stub_readme = textwrap.dedent(f"""\
        # rskill-stub
        > A stub that still has a TODO inside.

        <!-- {DELEGATION_MARKER_NAME}: {canonical_dir} -->

        TODO: write the action / state contract before publish.

        Upstream: <https://huggingface.co/example/stub>
    """)
    (stub_dir / "README.md").write_text(stub_readme, encoding="utf-8")
    manifest = RSkillManifest.from_yaml(str(stub_dir / "rskill.yaml"))
    report = validate_rskill_docs(stub_dir, manifest)
    assert not report.is_valid
    placeholders = [i for i in report.errors if i.field == "readme.placeholder"]
    assert placeholders


# ── Template scaffold fails publish-readiness ────────────────────────────────


def test_template_scaffold_fails_publish_readiness() -> None:
    """The bare ``rskills/template/`` scaffold MUST fail the publish gate.

    Catches the regression where the template's docs accidentally start
    looking like a real, ready-to-publish rSkill — that would let a
    user run ``python tools/rskill_publisher.py rskills/template/
    --publish`` and upload a placeholder package.
    """
    repo_root = Path(__file__).resolve().parents[2]
    template_dir = repo_root / "rskills" / "template"
    manifest = RSkillManifest.from_yaml(str(template_dir / "rskill.yaml"))
    report = validate_rskill_docs(template_dir, manifest)
    assert not report.is_valid, (
        "The template scaffold MUST fail the publish gate; if it just started "
        "passing, the placeholder sentinels were probably stripped from "
        "rskills/template/README.md or rskill.yaml — re-add them."
    )


# ── In-tree regression guard ────────────────────────────────────────────────


def _intree_skill_dirs() -> list[Path]:
    """Return every ``rskills/<id>/`` dir except the scaffold template."""
    repo_root = Path(__file__).resolve().parents[2]
    rskills_dir = repo_root / "rskills"
    out: list[Path] = []
    for child in sorted(rskills_dir.iterdir()):
        if not child.is_dir():
            continue
        if child.name == "template":
            continue
        if not (child / "rskill.yaml").is_file():
            continue
        out.append(child)
    return out


@pytest.mark.parametrize("skill_dir", _intree_skill_dirs(), ids=lambda p: p.name)
def test_every_intree_rskill_passes_publish_readiness(skill_dir: Path) -> None:
    """Regression guard: every shipped rSkill is publish-ready.

    If this fails after a refactor of the validator, either the
    validator tightened beyond the in-tree skills (update them) or an
    in-tree skill regressed (update the skill).
    """
    manifest = RSkillManifest.from_yaml(str(skill_dir / "rskill.yaml"))
    report = validate_rskill_docs(skill_dir, manifest)
    if not report.is_valid:
        rendered = "\n".join(f"  - [{i.field}] {i.message}" for i in report.errors)
        pytest.fail(f"in-tree rSkill {skill_dir.name} is not publish-ready:\n{rendered}")
